name: TradingPost
main: net.lethargiclion.tradingpost.TradingPost
version: 0.1a1
commands:
    tr:
        description: Allows you to use Trading Post features.
        permission: tradingpost.use
        permission-message: You do not have permission to use Trading Post.
        usage: Your command was invalid. Try /tr help
    tradmin:
        description: Allows you to use administrative Trading Post features.
        permission: tradingpost.admin
        permission-message: You do not have permission to use Trading Post admin commands.
        usage: /tradmin <command> ...
permissions:
    tradingpost.use:
        description: Grants access to all general Trading Post user commands.
        default: true
    tradingpost.admin:
        description: Grants access to all administrative Trading Post commands.
        default: op